updateBranch: true
deleteBranchAfterMerge: true
reportStatus: true
mergeMethod: merge

minApprovals:
  OWNER: 1
maxRequestedChanges:
  NONE: 0
blockingLabels:
- blocked

# Will merge whenever the above conditions are met, but also
# the owner has approved or merge label was added.

blockingTitleRegex: '\bWIP\b'
