policies:
  - type: commit
    spec:
      headerLength: 89
      dco: false
      gpg: false
      imperative: true
      maximumOfOneCommit: false
      requireCommitBody: false
      conventional:
        types:
          - chore
          - docs
          - refactor
          - style
          - test
          - fix
        scopes:
          - "scope"
  - type: license
    spec:
      includeSuffixes:
        - .go
      excludeSuffixes:
        - .deepcopy.go
      header: |
        /*
        Copyright 2019 Alexander Eldeib.
        */
