
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - keyvaults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - keyvaults/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - secretbundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - secretbundles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
