
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - keyvaults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - keyvaults/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - networkinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - networkinterfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - publicips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - publicips/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - redis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - redis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - resourcegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - resourcegroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - secretbundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - secretbundles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - securitygroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - securitygroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - servicebus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - servicebus/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - subnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - subnets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - trafficmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - trafficmanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - virtualnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.alexeldeib.xyz
  resources:
  - virtualnetworks/status
  verbs:
  - get
  - patch
  - update
