apiVersion: azure.alexeldeib.xyz/v1alpha1
kind: Redis
metadata:
  name: redis-sample
spec:
  subscriptionId: 6ab827b9-84a1-422a-96cb-dc60d60cb35b
  resourceGroup: test-rg-crd-2
  location: westus2
  name: ace-redis-10
  enableNonSslPort: false
  sku: 
    name: premium
    family: p
    capacity: 1
  targetSecret: sb-secret
  primaryKey: blah
  secondaryKey: blah2
---
# Applying this will automatically create the following object
# apiVersion: v1
# kind: Secret
# metadata:
#   name: redis-sample
#   namespace: default # matches what you applied
# data:
#   blah: $BASE64_ENCODED_PRIMARY_KEY
#   blah2: $BASE64_ENCODED_SECONDARY_KEY
