apiVersion: azure.alexeldeib.xyz/v1alpha1
kind: ServiceBusKey
metadata:
  name: sb-key
  namespace: default
spec:
  subscriptionId: eb4644c9-9cf4-4383-ac9f-ab2854720aef
  resourceGroup: some-rg
  name: some-servicebus-ns
  targetSecret: sb-sample # name of corev1.Secret object in same namespace
  primaryKey: blah # in sb-secret, the key blah will contain the primary key