apiVersion: azure.alexeldeib.xyz/v1alpha1
kind: TrafficManager
metadata:
  name: trafficmanager-sample
spec:
  name: test-tm-cli
  subscriptionID: 3f72cd65-6bb9-442c-b852-3a2b9bff1240
  resourceGroup: ace-test-rg
  profileStatus: enabled
  trafficRoutingMethod: weighted
  dnsConfig:
    relativeName: testtmnew
    ttl: 30
  monitorConfig:
    customHeaders:
    - name: host
      value: something.alexeldeib.io
    expectedStatusCodeRanges:
    - max: 308
      min: 200
    intervalInSeconds: 10
    path: /healthz
    port: 443
    protocol: HTTPS
    timeoutInSeconds: 5
    toleratedNumberOfFailures: 3
  endpoints:
  - name: google-1
    properties:
      target: google.com
      status: enabled
      weight: 1
      priority: 1
      endpointLocation: eastus
