apiVersion: azure.alexeldeib.xyz/v1alpha1
kind: VirtualNetwork
metadata:
  name: vnet-sample
spec:
  subscriptionId: 1398ff42-ce47-436f-a2fb-9c409830c092
  resourceGroup: ace-crd
  name: ace-vnet
  location: westus2
  addresses: 
  - 10.0.0.0/8
  - 192.168.0.0/24
