apiVersion: azure.alexeldeib.xyz/v1alpha1
kind: SecurityGroup
metadata:
  name: sg-sample
spec:
  subscriptionId: 1398ff42-ce47-436f-a2fb-9c409830c092
  resourceGroup: ace-crd
  name: ace-vnet
  location: eastus2
  rules:
  - name: test_rule
    protocol: tcp
    access: deny
    direction: inbound
    sourcePortRange: 1-65535
    destinationPortRange: "443"
    sourceAddressPrefix: "*"
    destinationAddressPrefix: "*"
    priority: 205
