apiVersion: azure.alexeldeib.xyz/v1alpha1
kind: ResourceGroup
metadata:
  name: rg-sample2
  namespace: default
spec:
  subscriptionId: eb4644c9-9cf4-4383-ac9f-ab2854720aef
  name: ace-sql-demo4
  location: eastus
---
apiVersion: azure.alexeldeib.xyz/v1alpha1
kind: SQLServer
metadata:
  name: sql-sample
  namespace: default
spec:
  subscriptionId: eb4644c9-9cf4-4383-ac9f-ab2854720aef
  resourceGroup: ace-sql-demo4
  name: ace-sql
  location: eastus
  allowAzureServiceAccess: true
