apiVersion: azure.alexeldeib.xyz/v1alpha1
kind: Subnet
metadata:
  name: subnet-sample
spec:
  subscriptionId: 1398ff42-ce47-436f-a2fb-9c409830c092
  resourceGroup: ace-crd
  network: ace-vnet
  name: ace-subnet
  subnet: 10.0.0.0/28
