apiVersion: azure.alexeldeib.xyz/v1alpha1
kind: ResourceGroup
metadata:
  name: rg-sample
spec:
  subscriptionId: bd6a4e14-55fa-4160-a6a7-b718d7a2c95c
  name: test-ctrl-jnfpbksf2g1k3z9z
  location: westus2
