apiVersion: azure.alexeldeib.xyz/v1alpha1
kind: SecretBundle
metadata:
  name: draft-oms
  namespace: draft
spec:
  name: draft-oms
  secrets:
    draftAAD.pem:
      kind: pkcs8
      vault: &draftkv draft-global-int-kv
      name: 9958bc96-c8e8-464e-8c82-486dd5390ebc
    kustoAAD.pem:
      kind: pkcs8
      vault: *draftkv
      name: cdec54a6-6ddf-439c-86a1-5206033d2892
    firstPartyAAD.pem: 
      kind: pkcs8
      vault: *draftkv
      name: api-int-loganalytics-io
    firstPartyOmsAad.pem:  
      kind: pkcs8
      vault: *draftkv
      name: firstparty-int-oms
    firstPartyOmsAad.cert:  
      kind: x509
      vault: *draftkv
      name: firstparty-int-oms
    firstPartyAiAad.pem:  
      kind: pkcs8
      vault: *draftkv
      name: firstparty-int-ai
    firstPartyAiAad.cert:  
      kind: x509
      vault: *draftkv
      name: firstparty-int-ai
    draftAADClientThumbprint.txt:
      kind: sha
      vault: *draftkv
      name: 9958bc96-c8e8-464e-8c82-486dd5390ebc
    kustoAADClientThumbprint.txt:
      kind: sha
      vault: *draftkv
      name: cdec54a6-6ddf-439c-86a1-5206033d2892
    firstPartyAADClientThumbprint.txt:
      kind: sha
      vault: *draftkv
      name: api-int-loganalytics-io
    firstPartyOmsAadClientThumbprint.txt:
      kind: sha
      vault: *draftkv
      name: firstparty-int-oms
    firstPartyAiAadClientThumbprint.txt:
      kind: sha
      vault: *draftkv
      name: firstparty-int-ai
# ---
# apiVersion: azure.alexeldeib.xyz/v1alpha1
# kind: RedisKey
# metadata:
#   name: cacheRedisKey
#   namespace: &namespace draft
# spec:
#   subscriptionId: bd6a4e14-55fa-4160-a6a7-b718d7a2c95c
#   resourceGroup: draft-global-int
#   name: draft-global-int-cache
#   targetSecret: draft-oms
#   primaryKey: cacheRedisKey.txt
# ---
# apiVersion: azure.alexeldeib.xyz/v1alpha1
# kind: RedisKey
# metadata:
#   name: throttleRedisCacheKeyNew
#   namespace: draft
# spec:
#   subscriptionId: bd6a4e14-55fa-4160-a6a7-b718d7a2c95c
#   resourceGroup: draft-global-int
#   name: draft-global-int-throttle2
#   targetSecret: draft-oms
#   primaryKey: throttleRedisCacheKeyNew.txt
# ---
# apiVersion: azure.alexeldeib.xyz/v1alpha1
# kind: RedisKey
# metadata:
#   name: OmsCacheRedisKey
#   namespace: draft
# spec:
#   subscriptionId: 5d3d4b48-4355-49ad-890d-c49efc3a211d
#   resourceGroup: draft-int-genesys-cache
#   name: oms-draft-int-genesys-int-cache
#   targetSecret: draft-oms
#   primaryKey: OmsCacheRedisKey.txt
# ---
# apiVersion: azure.alexeldeib.xyz/v1alpha1
# kind: RedisKey
# metadata:
#   name: AiCacheRedisKey
#   namespace: draft
# spec:
#   subscriptionId: 5d3d4b48-4355-49ad-890d-c49efc3a211d
#   resourceGroup: draft-int-genesys-cache
#   name: ai-draft-int-genesys-int-cache
#   targetSecret: draft-oms
#   primaryKey: AiCacheRedisKey.txt
# ---
# apiVersion: azure.alexeldeib.xyz/v1alpha1
# kind: RedisKey
# metadata:
#   name: RcCacheRedisKey
#   namespace: draft
# spec:
#   subscriptionId: 5d3d4b48-4355-49ad-890d-c49efc3a211d
#   resourceGroup: draft-int-genesys-cache
#   name: rc-draft-int-genesys-int-cache
#   targetSecret: draft-oms
#   primaryKey: RcCacheRedisKey.txt
# ---
# apiVersion: azure.alexeldeib.xyz/v1alpha1
# kind: RedisKey
# metadata:
#   name: CommonCacheRedisKey
#   namespace: draft
# spec:
#   subscriptionId: 5d3d4b48-4355-49ad-890d-c49efc3a211d
#   resourceGroup: draft-int-genesys-cache
#   name: rc-draft-int-genesys-int-cache
#   targetSecret: draft-oms
#   primaryKey: CommonCacheRedisKey.txt
# ---
# apiVersion: azure.alexeldeib.xyz/v1alpha1
# kind: RedisKey
# metadata:
#   name: ResponseCacheRedisKey
#   namespace: draft
# spec:
#   subscriptionId: 5d3d4b48-4355-49ad-890d-c49efc3a211d
#   resourceGroup: draft-int-genesys-cache
#   name: response-draft-int-genesys-int-cache
#   targetSecret: draft-oms
#   primaryKey: ResponseCacheRedisKey.txt
---
apiVersion: azure.alexeldeib.xyz/v1alpha1
kind: TLSSecret
metadata:
  name: api.int.loganalytics.io
  namespace: draft
spec:
  vault: draft-global-int-kv
  name: api-loganalytics-io-tls
