# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/azure.alexeldeib.xyz_resourcegroups.yaml
- bases/azure.alexeldeib.xyz_keyvaults.yaml
- bases/azure.alexeldeib.xyz_secrets.yaml
- bases/azure.alexeldeib.xyz_secretbundles.yaml
- bases/azure.alexeldeib.xyz_virtualnetworks.yaml
- bases/azure.alexeldeib.xyz_subnets.yaml
- bases/azure.alexeldeib.xyz_securitygroups.yaml
- bases/azure.alexeldeib.xyz_publicips.yaml
- bases/azure.alexeldeib.xyz_networkinterfaces.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_resourcegroups.yaml
#- patches/webhook_in_keyvaults.yaml
#- patches/webhook_in_secrets.yaml
#- patches/webhook_in_secretbundles.yaml
#- patches/webhook_in_virtualnetworks.yaml
#- patches/webhook_in_subnets.yaml
#- patches/webhook_in_securitygroups.yaml
#- patches/webhook_in_publicips.yaml
#- patches/webhook_in_networkinterfaces.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_resourcegroups.yaml
#- patches/cainjection_in_keyvaults.yaml
#- patches/cainjection_in_secrets.yaml
#- patches/cainjection_in_secretbundles.yaml
#- patches/cainjection_in_virtualnetworks.yaml
#- patches/cainjection_in_subnets.yaml
#- patches/cainjection_in_securitygroups.yaml
#- patches/cainjection_in_publicips.yaml
#- patches/cainjection_in_networkinterfaces.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
