name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: false
  branches:
    include:
      - master
      - ace/*
  tags:
    include:
      - v*
  paths:
    exclude:
      - README.md
      - docs/*
      - OWNERS

pr:
  autoCancel: true
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - docs/*
      - OWNERS

variables:
  GOPATH: '$(system.defaultWorkingDirectory)/gopath'
  GOBIN:  '$(system.defaultWorkingDirectory)/$(build.repository.name)/bin'
  GOROOT: '/usr/local/go1.12'

stages:
- stage: 
  displayName: 'Test stage'
  jobs:
  - job: setup    
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo '##vso[task.prependpath]$(GOROOT)/bin'
      displayName: 'Set up the Go workspace'
    - script: echo Hello, world!
      env:
        GO111MODULE: on
      displayName: 'Run a one-line script'
    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        echo $GO111MODULE
        echo $(go env)
        echo $(go version)
        go get golang.org/dl/go1.13.1
        go1.13.1 download
        go1.13.1 version
        go1.13.1 env
      displayName: 'Run a multi-line script'
      env:
        GO111MODULE: on
