
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: publicips.azure.alexeldeib.xyz
spec:
  group: azure.alexeldeib.xyz
  names:
    kind: PublicIP
    plural: publicips
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: PublicIP is the Schema for the publicips API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PublicIPSpec defines the desired state of PublicIP
          properties:
            location:
              description: Location osecurity group (e.g., eastus2)
              type: string
            name:
              description: Name is the name of the security group.
              type: string
            resourceGroup:
              description: ResourceGroup containsecurity group.
              type: string
            sku:
              description: SKU is either basic or standard, representing the SKU of
                the IP in Azure.
              type: string
            subscriptionId:
              description: SubscriptionID contains the Resource group. Is a GUID.
              type: string
          required:
          - location
          - name
          - resourceGroup
          - subscriptionId
          type: object
        status:
          description: PublicIPStatus defines the observed state of PublicIP
          properties:
            id:
              description: ID is the fully qualified Azure resource ID.
              type: string
            observedGeneration:
              description: ObservedGeneration is the iteration of user-provided spec
                which has already been reconciled. This is used to decide when to
                re-reconcile changes.
              format: int64
              type: integer
            provisioningState:
              description: ProvisioningState sync the provisioning status of the resource
                from Azure.
              type: string
          required:
          - id
          - observedGeneration
          - provisioningState
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
