
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: redis.azure.alexeldeib.xyz
spec:
  group: azure.alexeldeib.xyz
  names:
    categories:
    - all
    kind: Redis
    plural: redis
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Redis is the Schema for the redis API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RedisSpec defines the desired state of Redis
          properties:
            enableNonSslPort:
              type: boolean
            location:
              description: Location osecurity group (e.g., eastus2)
              type: string
            name:
              description: Name is the name of the security group.
              type: string
            primaryKey:
              description: PrimaryKey +optional
              type: string
            resourceGroup:
              description: ResourceGroup containsecurity group.
              type: string
            secondaryKey:
              description: SecondaryKey +optional
              type: string
            sku:
              properties:
                capacity:
                  description: 'Capacity of the cache to deploy. Valid values: for
                    C (Basic/Standard) family (0, 1, 2, 3, 4, 5, 6), for P (Premium)
                    family (1, 2, 3, 4).'
                  format: int32
                  type: integer
                family:
                  description: 'Family of corresponding SKU. Possible values include:
                    ''C'' (basic/standard), P (premium)'
                  type: string
                name:
                  description: 'Name of sku. Required for account creation; optional
                    for update. Possible values include: ''Basic'', ''Standard'',
                    ''Premium'''
                  type: string
              required:
              - capacity
              - family
              - name
              type: object
            subscriptionId:
              description: SubscriptionID contains the Resource group. Is a GUID.
              type: string
            targetSecret:
              description: TargetSecret +optional
              type: string
          required:
          - enableNonSslPort
          - location
          - name
          - resourceGroup
          - sku
          - subscriptionId
          type: object
        status:
          description: RedisStatus defines the observed state of Redis
          properties:
            id:
              description: ID is the fully qualified Azure resource ID.
              type: string
            observedGeneration:
              description: ObservedGeneration is the iteration of user-provided spec
                which has already been reconciled. This is used to decide when to
                re-reconcile changes.
              format: int64
              type: integer
            provisioningState:
              description: ProvisioningState sync the provisioning status of the resource
                from Azure.
              type: string
          required:
          - observedGeneration
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
