
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: storageaccounts.azure.alexeldeib.xyz
spec:
  group: azure.alexeldeib.xyz
  names:
    categories:
    - all
    kind: StorageAccount
    listKind: StorageAccountList
    plural: storageaccounts
    shortNames:
    - storage
    singular: storageaccount
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: StorageAccount is the Schema for the publicips API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: StorageAccountSpec defines the desired state of StorageAccount
          properties:
            location:
              description: Location of resource group (e.g., eastus2)
              type: string
            name:
              description: Name is the name of the resource.
              type: string
            primaryKey:
              description: PrimaryKey +optional
              type: string
            resourceGroup:
              description: ResourceGroup containing the resource.
              type: string
            subscriptionId:
              description: SubscriptionID contains the Resource group. Is a GUID.
              type: string
            targetSecret:
              description: TargetSecret +optional
              type: string
          required:
          - location
          - name
          - resourceGroup
          - subscriptionId
          type: object
        status:
          description: StorageAccountStatus defines the observed state of StorageAccount
          properties:
            id:
              description: ID is the fully qualified Azure resource ID.
              type: string
            provisioningState:
              description: ProvisioningState sync the provisioning status of the resource
                from Azure.
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
