
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: trafficmanagers.azure.alexeldeib.xyz
spec:
  group: azure.alexeldeib.xyz
  names:
    categories:
    - all
    kind: TrafficManager
    listKind: TrafficManagerList
    plural: trafficmanagers
    shortNames:
    - tm
    singular: trafficmanager
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: TrafficManager is the Schema for the trafficmanagers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: TrafficManagerSpec defines the desired state of TrafficManager
          properties:
            dnsConfig:
              properties:
                relativeName:
                  type: string
                ttl:
                  format: int64
                  type: integer
              required:
              - relativeName
              type: object
            endpoints:
              items:
                properties:
                  location:
                    type: string
                  name:
                    type: string
                  properties:
                    properties:
                      customHeaders:
                        description: CustomHeaders - List of custom headers.
                        items:
                          properties:
                            name:
                              description: Name - Header name.
                              type: string
                            value:
                              description: Value - Header value.
                              type: string
                          type: object
                        type: array
                      endpointLocation:
                        description: EndpointLocation - Specifies the location of
                          the external or nested endpoints when using the 'Performance'
                          traffic routing method.
                        type: string
                      priority:
                        description: Priority - The priority of this endpoint when
                          using the 'Priority' traffic routing method. Possible values
                          are from 1 to 1000, lower values represent higher priority.
                          This is an optional parameter.  If specified, it must be
                          specified on all endpoints, and no two endpoints can share
                          the same priority value.
                        format: int64
                        type: integer
                      target:
                        description: Target - The fully-qualified DNS name or IP address
                          of the endpoint. Traffic Manager returns this value in DNS
                          responses to direct traffic to this endpoint.
                        type: string
                      weight:
                        description: Weight - The weight of this endpoint when using
                          the 'Weighted' traffic routing method. Possible values are
                          from 1 to 1000.
                        format: int64
                        type: integer
                    type: object
                required:
                - location
                - name
                - properties
                type: object
              type: array
            monitorConfig:
              properties:
                customHeaders:
                  description: CustomHeaders - List of custom headers.
                  items:
                    properties:
                      name:
                        description: Name - Header name.
                        type: string
                      value:
                        description: Value - Header value.
                        type: string
                    type: object
                  type: array
                expectedStatusCodeRanges:
                  description: ExpectedStatusCodeRanges - List of expected status
                    code ranges.
                  items:
                    properties:
                      max:
                        description: Max - Max status code.
                        format: int32
                        type: integer
                      min:
                        description: Min - Min status code.
                        format: int32
                        type: integer
                    type: object
                  type: array
                intervalInSeconds:
                  description: IntervalInSeconds - The monitor interval for endpoints
                    in this profile. This is the interval at which Traffic Manager
                    will check the health of each endpoint in this profile.
                  format: int64
                  type: integer
                path:
                  description: Path - The path relative to the endpoint domain name
                    used to probe for endpoint health.
                  type: string
                port:
                  description: Port - The TCP port used to probe for endpoint health.
                  format: int64
                  type: integer
                protocol:
                  description: 'Protocol - The protocol (HTTP, HTTPS or TCP) used
                    to probe for endpoint health. Possible values include: ''HTTP'',
                    ''HTTPS'', ''TCP'''
                  type: string
                timeoutInSeconds:
                  description: TimeoutInSeconds - The monitor timeout for endpoints
                    in this profile. This is the time that Traffic Manager allows
                    endpoints in this profile to response to the health check.
                  format: int64
                  type: integer
                toleratedNumberOfFailures:
                  description: ToleratedNumberOfFailures - The number of consecutive
                    failed health check that Traffic Manager tolerates before declaring
                    an endpoint in this profile Degraded after the next failed health
                    check.
                  format: int64
                  type: integer
              type: object
            name:
              type: string
            profileStatus:
              type: string
            resourceGroup:
              type: string
            subscriptionID:
              type: string
            trafficRoutingMethod:
              type: string
          required:
          - endpoints
          - name
          - profileStatus
          - resourceGroup
          - subscriptionID
          - trafficRoutingMethod
          type: object
        status:
          description: TrafficManagerStatus defines the observed state of TrafficManager
          properties:
            endpointStatus:
              items:
                properties:
                  monitorStatus:
                    type: string
                type: object
              type: array
            fqdn:
              type: string
            id:
              description: ID is the fully qualified Azure resource ID.
              type: string
            profileMonitorStatus:
              type: string
            profileStatus:
              type: string
          required:
          - id
          - profileMonitorStatus
          - profileStatus
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
