
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: rediskeys.azure.alexeldeib.xyz
spec:
  group: azure.alexeldeib.xyz
  names:
    categories:
    - all
    kind: RedisKey
    listKind: RedisKeyList
    plural: rediskeys
    shortNames:
    - rediskey
    singular: rediskey
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: RedisKey is the Schema for the publicips API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RedisKeySpec defines the desired state of RedisKey
          properties:
            name:
              description: Name is the name of some resource in Azure.
              type: string
            primaryKey:
              description: PrimaryKey +optional
              type: string
            resourceGroup:
              description: ResourceGroup is the name of an Azure resource group.
              type: string
            secondaryKey:
              description: SecondaryKey +optional
              type: string
            subscriptionId:
              description: SubscriptionID contains the resource group. Is a GUID.
              type: string
            targetSecret:
              description: TargetSecret
              type: string
          required:
          - name
          - resourceGroup
          - subscriptionId
          - targetSecret
          type: object
        status:
          description: RedisKeyStatus defines the observed state of RedisKey
          properties:
            provisioningState:
              description: ProvisioningState sync the provisioning status of the resource
                from Azure.
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
