
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: sqlfirewalls.azure.alexeldeib.xyz
spec:
  group: azure.alexeldeib.xyz
  names:
    categories:
    - all
    kind: SQLFirewallRule
    plural: sqlfirewalls
    shortNames:
    - sqlfw
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SQLFirewallRule is the Schema for the SQL server API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SQLFirewallRuleSpec defines the desired state of the firewall
            rule.
          properties:
            end:
              description: End is the end of the IP range to allow
              type: string
            name:
              description: Name is the name of the resource.
              type: string
            resourceGroup:
              description: ResourceGroup is the resourceg group containing the resource.
              type: string
            server:
              description: Server is the name of the SQL server this rule should apply
                to.
              type: string
            start:
              description: Start is the beginning of the IP range to allow
              type: string
            subscriptionId:
              description: SubscriptionID contains the resource group. Is a GUID.
              type: string
          required:
          - end
          - name
          - resourceGroup
          - server
          - start
          - subscriptionId
          type: object
        status:
          description: SQLFirewallRuleStatus defines the observed state of SQLFirewallRule
          properties:
            id:
              description: ID is the fully qualified Azure resource ID.
              type: string
            state:
              description: State sync the status of the resource from Azure.
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
