name: build + test cli/controller
on: [push]

jobs:
  build_manager:
    name: build manager
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build manager
        uses: docker://alexeldeib/kbtest:latest
        with:
          entrypoint: /scripts/mgr_build.sh
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  build_cli:
    name: build cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build cli
        uses: docker://alexeldeib/kbtest:latest
        with:
          entrypoint: /scripts/cli_build.sh
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
  test_manager:
    name: test manager
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        uses: docker://alexeldeib/kbtest:latest
        with:
          entrypoint: /scripts/mgr_test.sh
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
  test_cli:
    name: test cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        uses: docker://alexeldeib/kbtest:latest
        with:
          entrypoint: /scripts/cli_test.sh
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
  clean_test_manager:
    name: clean test manager
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          set -eux
          export PATH=$PATH:/usr/local/kubebuilder/bin
          go get golang.org/x/tools/cmd/goimports
          go get github.com/onsi/ginkgo/ginkgo
          go get sigs.k8s.io/kustomize/v3/cmd/kustomize@master
          go get sigs.k8s.io/kind@v0.5.1
          go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.0
          os=$(go env GOOS)
          arch=$(go env GOARCH)
          curl -sL https://go.kubebuilder.io/dl/2.0.0/${os}/${arch} -o kubebuilder_2.0.0_${os}_${arch}
          sudo mv ./kubebuilder_2.0.0_${os}_${arch}/bin /usr/local/kubebuilder
          ls -al /usr/local/kubebuilder
          ls -al /usr/local/kubebuilder/bin
          which kubebuilder
          which kustomize
          which controller-gen
          which kind 
          kind create cluster
          export KUBECONFIG=$(kind get kubeconfig-path --name="kind")
          make ci-manager
  clean_test_cli:
    name: clean test cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
        run: |
          set -eux
          export PATH=$PATH:/usr/local/kubebuilder/bin
          go get golang.org/x/tools/cmd/goimports
          go get github.com/onsi/ginkgo/ginkgo
          go get sigs.k8s.io/kustomize/v3/cmd/kustomize@master
          go get sigs.k8s.io/kind@v0.5.1
          go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.0
          os=$(go env GOOS)
          arch=$(go env GOARCH)
          curl -sL https://go.kubebuilder.io/dl/2.0.0/${os}/${arch} -o kubebuilder_2.0.0_${os}_${arch}
          sudo mv ./kubebuilder_2.0.0_${os}_${arch}/bin /usr/local/kubebuilder
          ls -al /usr/local/kubebuilder
          ls -al /usr/local/kubebuilder/bin
          which kustomize
          which controller-gen
          which kind 
          kind create cluster
          export KUBECONFIG=$(kind get kubeconfig-path --name="kind")
          make ci-cli