name: build + test cli/controller
on: [push]

jobs:
  build_manager:
    name: build manager
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build manager
        uses: docker://alexeldeib/kbtest:latest
        with:
          entrypoint: /scripts/mgr_build.sh
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  build_cli:
    name: build cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build cli
        uses: docker://alexeldeib/kbtest:latest
        with:
          entrypoint: /scripts/cli_build.sh
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
  test_manager:
    name: test manager
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        uses: docker://alexeldeib/kbtest:latest
        with:
          entrypoint: /scripts/mgr_test.sh
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
  test_cli:
    name: test cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        uses: docker://alexeldeib/kbtest:latest
        with:
          entrypoint: /scripts/cli_test.sh
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
